"""
PR Review using GitHub Copilot SDK
"""

import asyncio
import os
import shutil
import sys

from copilot import CopilotClient
from github import Auth, Github


async def get_pr_diff(repo_name: str, pr_number: int, github_token: str):
    try:
        g = Github(auth=Auth.Token(github_token))
        repo = g.get_repo(repo_name)
        pr = repo.get_pull(pr_number)

        diff = f"# PR #{pr_number}: {pr.title}\n\n"
        diff += f"**Description:** {pr.body or 'No description'}\n"
        changed = f"+{pr.additions} / -{pr.deletions}"
        diff += f"**Files Changed:** {pr.changed_files} ({changed})\n\n---\n\n"

        max_patch_chars = 300
        for file in pr.get_files():
            diff += f"\n## {file.filename} ({file.status})\n"
            diff += f"+{file.additions} / -{file.deletions}\n\n"
            if file.patch:
                patch = file.patch
                if len(patch) > max_patch_chars:
                    patch = patch[:max_patch_chars] + "\n... (truncated)"
                diff += f"```diff\n{patch}\n```\n\n"

        return diff, pr
    except Exception as e:
        print(f"Error fetching PR: {e}")
        sys.exit(1)


async def analyze_with_copilot(diff: str, github_token: str) -> str:
    copilot_path = shutil.which("copilot")
    config: dict = {"github_token": github_token}
    if copilot_path:
        config["cli_path"] = copilot_path

    client = CopilotClient(config)
    await client.start()

    try:
        session = await client.create_session({
            "model": "gpt-5.2-codex",
            "reasoning_effort": "xhigh",
            "streaming": True,
        })

        prompt = f"""以下のPull Requestをレビューしてください。

レビュー観点:
1. バグ・ロジックの問題
2. セキュリティ上の懸念
3. パフォーマンス
4. Pythonベストプラクティス
5. 良い点

---

{diff}"""

        response = await session.send_and_wait({"prompt": prompt}, timeout=300)
        result = ""
        if response and getattr(response, "data", None) and getattr(
            response.data, "content", None
        ):
            result = response.data.content
        else:
            result = "（Copilot からの応答なし）"

        await client.stop()
        return result

    except Exception as e:
        await client.stop()
        raise e


async def main():
    copilot_token = os.getenv("COPILOT_GITHUB_TOKEN")
    github_token = os.getenv("GITHUB_TOKEN")
    pr_number = os.getenv("PR_NUMBER")
    repository = os.getenv("REPOSITORY")

    if not all([copilot_token, github_token, pr_number, repository]):
        print("Missing required env vars")
        sys.exit(1)

    print(f"Analyzing PR #{pr_number} in {repository}")

    diff, pr = await get_pr_diff(repository, int(pr_number), github_token)
    analysis = await analyze_with_copilot(diff, copilot_token)

    comment = (
        f"## 🤖 Copilot Code Review\n\n{analysis}\n\n"
        "---\n*Generated by GitHub Copilot SDK*"
    )
    pr.create_issue_comment(comment)
    print("Review posted.")


if __name__ == "__main__":
    asyncio.run(main())
